apiVersion: v1
kind: ConfigMap
metadata:
  name: vets-service
  namespace: spring-petclinic
data:
  application-sit-yml: |
    server:
      port: 8080
    spring:
      application:
        name:  vets-service
      datasource:
        url: jdbc:mysql://mysql.default:3306/petclinic?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&verifyServerCertificate=false
        username: meshdemo
        password: meshdemo
      jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      zipkin:
          enabled: false
      sleuth:
        enabled: false
        web:
          servlet:
          enabled: false
    eureka:
      client:
        serviceUrl:
          defaultZone: http://127.0.0.1:13009/mesh/eureka
      instance:
        preferIpAddress: true
        lease-expiration-duration-in-seconds: 60

---

apiVersion: mesh.megaease.com/v1beta1
kind: MeshDeployment
metadata:
  namespace: spring-petclinic
  name: vets-service
spec:
  service:
    name: vets-service
    labels: {}
  deploy:
    replicas: 1
    selector:
      matchLabels:
        app: vets-service
    template:
      metadata:
        labels:
          app: vets-service
      spec:
        containers:
          - image: megaease/spring-petclinic-vets-service:latest
            name: vets-service
            imagePullPolicy: IfNotPresent
            lifecycle:
              preStop:
                exec:
                  command: ["sh", "-c", "sleep 10"]
            command: ["/bin/sh"]
            args: ["-c", "java -server -Xmx1024m -Xms1024m -Dspring.profiles.active=sit -Djava.security.egd=file:/dev/./urandom  org.springframework.boot.loader.JarLauncher"]
            resources:
              limits:
                cpu: 2000m
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
              - mountPath: /application/application-sit.yml
                name: configmap-volume-0
                subPath: application-sit.yml
            ports:
              - containerPort: 8080
        volumes:
          - configMap:
              defaultMode: 420
              items:
                - key: application-sit-yml
                  path: application-sit.yml
              name: vets-service
            name: configmap-volume-0

        restartPolicy: Always
