apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-petclinic
  name: vets-service
  annotations:
    mesh.megaease.com/service-name: "vets-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - image: megaease/spring-petclinic-vets-service:consul
          name: vets-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          command: ["/bin/sh"]
          args: ["-c", "java -server -Xmx1024m -Xms1024m -Dspring.profiles.active=sit -Djava.security.egd=file:/dev/./urandom  org.springframework.boot.loader.JarLauncher"]
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /application/application-sit.yml
              name: configmap-volume-0
              subPath: application-sit.yml
          ports:
            - containerPort: 8080
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application-sit-yml
                path: application-sit.yml
            name: vets-service
          name: configmap-volume-0
      restartPolicy: Always

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vets-service
  namespace: spring-petclinic
data:
  application-sit-yml: |
    server:
      port: 8080
    spring:
      datasource:
        schema: classpath*:db/hsqldb/schema.sql
        data: classpath*:db/hsqldb/data.sql
      jpa:
        open-in-view: false
        hibernate:
          ddl-auto: none
      application:
        name:  vets-service
      zipkin:
          enabled: false
      sleuth:
        enabled: false
        web:
          servlet:
          enabled: false
      cloud:
        consul:
          host: localhost
          port: 13009


