
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: visits-service
  namespace: spring-petclinic
data:
  application-sit-yml: |
    server:
      port: 8080
    spring:
      datasource:
        schema: classpath*:db/hsqldb/schema.sql
        data: classpath*:db/hsqldb/data.sql
      jpa:
        open-in-view: false
        hibernate:
          ddl-auto: none
      application:
        name:  visits-service
      zipkin:
          enabled: false
      sleuth:
        enabled: false
        web:
          servlet:
          enabled: false
    eureka:
      client:
        serviceUrl:
          defaultZone: http://127.0.0.1:13009/mesh/eureka
      instance:
        preferIpAddress: true
        lease-expiration-duration-in-seconds: 60

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-petclinic
  name: visits-service
  annotations:
    mesh.megaease.com/service-name: "visits-service"
    mesh.megaease.com/alive-probe-url: "http://localhost:9900/health"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - image: megaease/spring-petclinic-visits-service:latest
        name: visits-service
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        command: ["/bin/sh"]
        args: ["-c", "java -server -Xmx1024m -Xms1024m -Dspring.profiles.active=sit -Djava.security.egd=file:/dev/./urandom  org.springframework.boot.loader.JarLauncher"]
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
          - mountPath: /application/application-sit.yml
            name: configmap-volume-0
            subPath: application-sit.yml
        ports:
        - containerPort: 8080
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application-sit-yml
                path: application-sit.yml
            name: visits-service
          name: configmap-volume-0
      restartPolicy: Always
