---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-petclinic-api-gateway
  namespace: spring-petclinic
data:
  application-sit-yml: |
    server:
      port: 8080
    spring:
      zipkin:
          enabled: false
      sleuth:
        enabled: false
        web:
          servlet:
          enabled: false
      application:
        name:  pet-api-gateway
      cloud:
        loadbalancer:
          ribbon:
            enabled: true
        gateway:
          routes:
             - id: vets-service
               uri: lb://vets-service
               predicates:
                 - Path=/api/vet/**
               filters:
                 - StripPrefix=2
             - id: visits-service
               uri: lb://visits-service
               predicates:
                 - Path=/api/visit/**
               filters:
                 - StripPrefix=2
             - id: customers-service
               uri: lb://customers-service
               predicates:
                 - Path=/api/customer/**
               filters:
                 - StripPrefix=2
    eureka:
      client:
        serviceUrl:
          defaultZone: http://127.0.0.1:13009/mesh/eureka
      instance:
        preferIpAddress: true
        lease-expiration-duration-in-seconds: 60

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-petclinic
  name: api-gateway
  annotations:
    mesh.megaease.com/service-name: "api-gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: megaease/spring-petclinic-api-gateway:latest
        name: api-gateway
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        command: ["/bin/sh"]
        args: ["-c", "java -server -Xmx1024m -Xms1024m -Dspring.profiles.active=sit -Djava.security.egd=file:/dev/./urandom org.springframework.boot.loader.JarLauncher" ]
        volumeMounts:
          - mountPath: /application/application-sit.yml
            name: configmap-volume-0
            subPath: application-sit.yml
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 8080
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application-sit-yml
                path: application-sit.yml
            name: spring-petclinic-api-gateway
          name: configmap-volume-0
      restartPolicy: Always

